import express from "express";
import bodyParser from "body-parser";
import cors from 'cors';
import setRoutes from "./routes";
import socketio from "./socket";
import http from 'http';
const app = express();
const server = http.createServer(app);
app.use(bodyParser.json());
app.use(cors());
setRoutes(app);
socketio(server);
export default server;